#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux 
# During the Install deployment lifecycle event (which occurs between the 
#   BeforeInstall and AfterInstall events), copy the specified files 
#   in "source" starting from the root of the revision's file bundle 
#   to "destination" on the Amazon EC2 instance.
# Specify multiple "source" and "destination" pairs if you want to copy 
#   from multiple sources or to multiple destinations.
# If you are not copying any files to the Amazon EC2 instance, then remove the
#   "files" section altogether. A blank or incomplete "files" section
#   may cause associated deployments to fail.
files:
  - source: .
    destination: /home/ubuntu/rende
file_exists_behavior: OVERWRITE
# hooks:
#   ApplicationStop:
#     - location: scripts/AppStop.sh
#       timeout: 30
#       runas: root
#   ApplicationStart:
#     - location: scripts/AppStart.sh  
#       timeout: 30
#       runas: root