version: 0.2

env:
  shell: bash
#   variables:
#     JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#   parameter-store:
#     LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Updating...
      - apt-get update
  pre_build:
    commands:
      - echo Installing npm Dependencies
      - npm install
      - wget https://go.dev/dl/go1.21.0.linux-386.tar.gz
      - tar -xzf go1.21.0.linux-386.tar.gz
      - ./go/bin/go version
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run build
      - cd server && ./go/bin/go build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
  # - '**/*'
  - appspec.yml
  - server/**/*
  - scripts/*
  - public/**/*
  name: rende-prod-$(date +%Y-%m-%d)


# reports:
#   arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
#     files:
#       - "**/*"
#     base-directory: 'target/tests/reports'
#     discard-paths: no
#   reportGroupCucumberJson:
#     files:
#       - 'cucumber/target/cucumber-tests.xml'
#     discard-paths: yes
#     file-format: CUCUMBERJSON # default is JUNITXML
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
#   discard-paths: yes
#   secondary-artifacts:
#     artifact1:
#       files:
#         - target/artifact-1.0.jar
#       discard-paths: yes
#     artifact2:
#       files:
#         - target/artifact-2.0.jar
#       discard-paths: yes
# cache:
#   paths:
#     - '/root/.m2/**/*'
